// API 路径表（与模块 6229 常量一致）
export const API_PATHS = {
  setting: "setting",
  payment: "payment",
  adFree: "ad_free",
  coinBuyCharge: "coin_buy_charge",
  coinBuyComics: "coin_buy_comics",
  novelCoinBuy: "coin_buy_nc",
  login: "login",
  logout: "logout",
  register: "register",
  tasks: "tasks",
  coin: "coin",
  daily: "daily",
  dailyCheck: "daily_chk",
  dailyList: "daily_list",
  search: "search",
  album: "album",
  chapter: "chapter",
  comicRead: "comic_read",
  latest: "latest",
  week: "week",
  categories: "categories",
  forum: "forum",
  blogs: "blogs",
  novels: "novels",
  userEdit: "useredit",
  favorite: "favorite",
  watchList: "watch_list",
  randomRecommend: "random_recommend",
  categoriesFilter: "categories/filter",
  weekFilter: "week/filter",
  comment: "comment",
  commentVote: "comment_vote",
  commentDelete: "comment_delete",
  hotTags: "hot_tags"
} as const;

export type ApiPathKey = keyof typeof API_PATHS;
